addons:
    firefox: 'latest-nightly'
    apt:
        packages:
            - xvfb
language: node_js
node_js: 
    - "7.4.0"
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - make xpi
    - npm test

